### ISSUE TITLE
saytini footer qismida buttomlarda hatolik bor

### ISSUE THREAD

**Issue by frontendoniyorbek** [MIRZOULUGBEK9008/account-selfmade#1]
https://github.com/MIRZOULUGBEK9008/account-selfmade/blob/ccc5ee84ef68fd9efcafcc7280ac0ac2463c1884/index.html#L63
https://prnt.sc/Ke8TB4HUwho3
ikkala buttonda ham tabiy pedding bor shuni padding:0; ga tenglab qo'yish kerak

**Comment by MIRZOULUGBEK9008** [comment]
#fix
